[build]
  base = "tinlake-ui"
  command = "yarn export"
  publish = "out"
  functions = "functions"
  environment = { NETLIFY_USE_YARN = "true" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
  
