[build]
  base = "onboarding-ui"
  command = "yarn build"
  publish = "out"
  environment = { NETLIFY_USE_YARN = "true" }

[[redirects]]
  from = "/"
  to = "https://tinlake.centrifuge.io/onboarding"
  status = 302
  force = false
