version: '3'
services:
  tinlake:
    build:
      context: ../lib/tinlake-deploy
      dockerfile: Dockerfile
    # image: centrifugeio/tinlake-in-a-box:5a4c5645
    ports:
     - "8545:8545"
    # expose:
    #   - "8545"
  ui:
    image: tinlake-ui # built locally in the tinlake-ui repo
    # build:
    #   context: ../lib/tinlake-ui
    #   dockerfile: docker/Dockerfile
    # expose:
    #   - "3000"
    ports:
     - "3000:3000"
  # tests:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile
  #   volumes:
  #     - "../screenshots:/screenshots"
  #   depends_on:
  #     - ui
      # - tinlake