name: 'tinlake-bot'
on: 
  pull_request:
    paths:
    - 'tinlake-bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install

      # Build
      - run: yarn run build
        working-directory: ./tinlake-bot

  push:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get image tag
        id: tag
        run: echo "::set-output name=TAG_NAME::$(echo "$(git rev-parse --abbrev-ref HEAD)-$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)")"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./tinlake-bot/docker/Dockerfile
          push: true
          tags: centrifugeio/tinlake-bot:latest
          # tags: centrifugeio/tinlake-bot:${{ steps.tag.outputs.TAG_NAME }}
