name: 'tinlake-ui Pull Request'
on:
  pull_request:
    paths:
      - 'tinlake-ui/**'
      - 'tinlake.js/**'
      - '.github/workflows/tinlake-ui-pull-request.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tinlake-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache Yarn Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - run: yarn format:check
      
      - name: Cache Next.js Bundle
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/tinlake-ui/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Lint
        run: yarn lint

      - name: Build
        run: |
          cp .env.mainnet-example .env
          yarn export
